### ISSUE TITLE
Update recaptcha to latest google solution

### ISSUE THREAD

**Issue by bdejong** [MTG/freesound#693] opened 2015-11-10 09:14 UTC
Our captcha should really be replaced by the latest google solution (the "I am not a robot" one). The current one is rather old-school by now and people are actually having trouble with it...

**Comment by alastair** [comment] 2015-11-16 10:47
duplicate of https://github.com/MTG/freesound/issues/626

**Closed by alastair** 2015-11-16 10:47 UTC
