### ISSUE TITLE
Delete non-confirmed user accounts with permanent bounced signup emails

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#1215] opened 2018-07-09 09:08 UTC
Now that we receive bounce notifications for emails, we can be sure if a user will never sign in to an inactive account. We should make a management command that looks for user accounts
 * Created more than 1 month ago
 * Never signed in to
 * Has a permanent bounce notification
and delete them

The idea of only selecting accounts more than 1 month old is to give users the chance to contact support and have them connected activated if possible. Maybe this is not as important if we know that the emails bounced, because it's unlikely that we could find the account if the user signed up originally with an incorrect email address.

**Comment by philtgun** [comment] 2018-07-09 12:33
Duplicate of #1199

**Closed by philtgun** 2018-07-09 12:33 UTC
