### ISSUE TITLE
ValueError: A string literal cannot contain NUL (0x00) characters.

### ISSUE THREAD

**Issue by ffont** [MTG/freesound#1162] opened 2018-04-03 07:59 UTC
https://logserver.mtg.upf.edu/sentry/freesound-web/issues/1077/

```
ValueError: A string literal cannot contain NUL (0x00) characters.
(27 additional frame(s) were not displayed)
...
  File "utils/session_checks.py", line 36, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "accounts/views.py", line 93, in login
    response = LoginView.as_view(template_name=template_name, authentication_form=authentication_form)(request)
  File "accounts/modelbackend.py", line 53, in authenticate
    user = User.objects.get(username__iexact=username)

ValueError: A string literal cannot contain NUL (0x00) characters.
```

**Comment by alastair** [comment] 2020-06-02 16:35
Duplicate of https://github.com/MTG/freesound/issues/1224

**Closed by alastair** 2020-06-02 16:35 UTC
Labels: Bug
