### ISSUE TITLE
IntegrityError: new row for relation "sounds_sound" violates check constraint "sounds_sound_num_comments_check"

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#819] opened 2017-03-17 12:18 UTC
Sounds num_comments is being lowered less than 0.
It looks like there are 2 things to check here:

 1. Don't decrease the count less than 0
 2. Why is the comment count 0? Is it because we have some sounds which have comments but don't have the correct value in `num_comments`, or is it because a user is double-clicking and causing 2 requests?

https://logserver.mtg.upf.edu/sentry/freesound-web/issues/581/

```
IntegrityError: new row for relation "sounds_sound" violates check constraint "sounds_sound_num_comments_check"
DETAIL:  Failing row contains (259527, 4452041, 2014-12-27 00:41:28.717857+01, NY Steam Radiator.flac, /home/fsweb/freesound/freesound-data/sounds/259/259527_4452041.f..., 259527__mr-roboto24__ny-steam-radiator, Clicks, hiss and various sounds of a New York City steam radiato..., null, 2, null, null, flac, 396.37, 2067, 24, 44100, 73357252, 2, d328c1fc9710e8c6231c40ebb3a559b5, t, OK, null, null, f, OK, null, null, OK, OK, -1, 156, 10, 1, cdc0bfb0, null, FI, f).

(14 additional frame(s) were not displayed)
...
  File "comments/views.py", line 43, in delete
    comment.delete()
  File "comments/models.py", line 48, in on_delete_comment
    instance.content_object.post_delete_comment()
  File "sounds/models.py", line 625, in post_delete_comment
    self.save()

IntegrityError: new row for relation "sounds_sound" violates check constraint "sounds_sound_num_comments_check"
DETAIL:  Failing row contains (259527, 4452041, 2014-12-27 00:41:28.717857+01, NY Steam Radiator.flac, /home/fsweb/freesound/freesound-data/sounds/259/259527_4452041.f..., 259527__mr-roboto24__ny-steam-radiator, Clicks, hiss and various sounds of a New York City steam radiato..., null, 2, null, null, flac, 396.37, 2067, 24, 44100, 73357252, 2, d328c1fc9710e8c6231c40ebb3a559b5, t, OK, null, null, f, OK, null, null, OK, OK, -1, 156, 10, 1, cdc0bfb0, null, FI, f).

```

**Comment by ffont** [comment] 2017-07-05 14:18
Duplicate of https://github.com/MTG/freesound/issues/894

**Closed by ffont** 2017-07-05 14:18 UTC
Labels: Bug
