### ISSUE TITLE
Web-based API browser doesn't work in www.freesound.org

### ISSUE THREAD

**Issue by alastair** [MTG/freesound#965] opened 2017-09-28 15:23 UTC
Continuing from #961

If a user visits freesound.org/apiv2 in a web browser they get an interactive documentation/api browser tool.
They must be logged in for this, but if they visit with www.freesound.org then they won't have a session cookie, and get an error.
We want to redirect webbrowser users from www. to nowww. We can do this in [`GenericAPIView.initial`](https://github.com/MTG/freesound/blob/91c1d206d1ec5b5b633c180eef1f18e54a393910/apiv2/apiv2_utils.py#L71) using the value of `contains_www` and if the renderer is set to `BrowsableAPIRenderer`. If so, we should issue a redirect to nowww.

**Comment by ffont** [comment] 2017-11-15 10:38
After deploying to production we manually tested this functionality and it is not working when users are not logged in. @andrebola do you remember checking if `finalize_response` is called even if users are not logged in? I'll remove the "merged" label as this issue needs more work.

**Comment by andrebola** [comment] 2017-11-15 12:36
@ffont the problem is that when the code of finalize_response was moved to a new method then the returned value is lost. 

So, this line should be something like `response = self.redirect_to_nowww_if_needed(request, response)`

https://github.com/MTG/freesound/pull/982/files#diff-7c0184a36b103db6a6f6af55a7e067d2R137

**Closed** 2017-11-16 16:55 UTC
Labels: Bug, Merged
