### ISSUE TITLE
Sounds that are moderated never show up at the top of the new sounds list

### ISSUE THREAD

**Issue by AlienXXX-Freesound** [MTG/freesound#552] opened 2013-11-25 16:29 UTC
Since moderation always takes a while, sounds that are moderated never show up at the top of the new sounds list.The top of this list is always taken up by sounds from users who are whitelisted.

If the list is sorted by date the sound becomes available in the database (rather than upload date), a mix of sounds from whitelist and non-whitelist users would appear on this list which would be a fairer representation of the number of recent uploads.

**Comment by ffont** [comment] 2016-06-01 10:33
Closing this one as this is a duplicate of #632

**Closed by ffont** 2016-06-01 10:33 UTC
Labels: High, Improvement, _Sounds
